// Code generated by go-swagger; DO NOT EDIT.

package reloads

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new reloads API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for reloads API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetReload returns one h a proxy reload status

Returns one HAProxy reload status.
*/
func (a *Client) GetReload(params *GetReloadParams, authInfo runtime.ClientAuthInfoWriter) (*GetReloadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetReloadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getReload",
		Method:             "GET",
		PathPattern:        "/services/haproxy/reloads/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetReloadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetReloadOK), nil

}

/*
GetReloads returns list of h a proxy reloads

Returns a list of HAProxy reloads.
*/
func (a *Client) GetReloads(params *GetReloadsParams, authInfo runtime.ClientAuthInfoWriter) (*GetReloadsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetReloadsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getReloads",
		Method:             "GET",
		PathPattern:        "/services/haproxy/reloads",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetReloadsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetReloadsOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
