linters-settings:
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 42
  cyclop:
    max-complexity: 42
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 2
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: true
linters:
  enable-all: true
  disable:
    - dupl
    - exhaustive
    - funlen
    - gci
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godot
    - lll
    - nestif
    - nlreturn
    - wrapcheck
    - wsl
    - nakedret
    - paralleltest
    - testpackage
    - varnamelen
    - exhaustruct
    - nonamedreturns
    - forcetypeassert
    - rowserrcheck #rowserrcheck is disabled because of generics
    - sqlclosecheck #rowserrcheck is disabled because of generics
    - wastedassign #rowserrcheck is disabled because of generics
    - ireturn
    - tagliatelle
    - noctx
    - errorlint
    - contextcheck
    - godox
    - containedctx
    - unused
    - unparam
    - prealloc
    - forbidigo
    - errcheck
    - gocritic
    - tagalign
    - depguard
    - mnd
    - gomnd
    - err113
    - execinquery
    - exportloopref

issues:
  exclude:
    # bugs of typecheck linter
    - "undeclared name: `shellquote`"
    - 'github.com/kballard/go-shellquote" imported but not used'
    - 'github.com/haproxytech/client-native/v6/config-parser/types" imported but not used'
  exclude-rules:
    - linters:
        - staticcheck
      text: "duplicate struct tag"
    - linters:
        - gosec
      text: "G[501]"
    - linters:
        - gosec
      text: "G[404]"
  exclude-dirs:
    - test
