version: "2"
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - depguard
    - dupl
    - err113
    - errcheck
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - godox
    - ireturn
    - lll
    - mnd
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - prealloc
    - recvcheck
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - testpackage
    - unparam
    - unused
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 42
    dupl:
      threshold: 200
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 42
    revive:
      rules:
        - name: var-naming
          severity: warning
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: duplicate struct tag
      - linters:
          - gosec
        text: G[501]
      - linters:
          - gosec
        text: G[404]
      - path: (.+)\.go$
        text: 'undeclared name: `shellquote`'
      - path: (.+)\.go$
        text: github.com/kballard/go-shellquote" imported but not used
      - path: (.+)\.go$
        text: github.com/haproxytech/client-native/v6/config-parser/types" imported but not used
    paths:
      - test
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - test
      - third_party$
      - builtin$
      - examples$
