linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - golint
    - gocritic
    - stylecheck
    - goimports
    - gosec
    - unconvert
  disable:
    - maligned
    - prealloc
    - gochecknoglobals

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "duplicate struct tag"
    - linters:
        - gosec
      text: "G[501]"

run:
  skip-dirs:
    - test
