// Code generated by go-swagger; DO NOT EDIT.

package tcp_request_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/haproxytech/models"
)

// GetTCPRequestRulesReader is a Reader for the GetTCPRequestRules structure.
type GetTCPRequestRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTCPRequestRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTCPRequestRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetTCPRequestRulesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetTCPRequestRulesOK creates a GetTCPRequestRulesOK with default headers values
func NewGetTCPRequestRulesOK() *GetTCPRequestRulesOK {
	return &GetTCPRequestRulesOK{}
}

/*GetTCPRequestRulesOK handles this case with default header values.

Successful operation
*/
type GetTCPRequestRulesOK struct {
	Payload *GetTCPRequestRulesOKBody
}

func (o *GetTCPRequestRulesOK) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/tcp_request_rules][%d] getTcpRequestRulesOK  %+v", 200, o.Payload)
}

func (o *GetTCPRequestRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetTCPRequestRulesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTCPRequestRulesDefault creates a GetTCPRequestRulesDefault with default headers values
func NewGetTCPRequestRulesDefault(code int) *GetTCPRequestRulesDefault {
	return &GetTCPRequestRulesDefault{
		_statusCode: code,
	}
}

/*GetTCPRequestRulesDefault handles this case with default header values.

General Error
*/
type GetTCPRequestRulesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get TCP request rules default response
func (o *GetTCPRequestRulesDefault) Code() int {
	return o._statusCode
}

func (o *GetTCPRequestRulesDefault) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/configuration/tcp_request_rules][%d] getTCPRequestRules default  %+v", o._statusCode, o.Payload)
}

func (o *GetTCPRequestRulesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetTCPRequestRulesOKBody get TCP request rules o k body
swagger:model GetTCPRequestRulesOKBody
*/
type GetTCPRequestRulesOKBody struct {

	// version
	Version int64 `json:"_version,omitempty"`

	// data
	// Required: true
	Data models.TCPRequestRules `json:"data"`
}

// Validate validates this get TCP request rules o k body
func (o *GetTCPRequestRulesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTCPRequestRulesOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("getTcpRequestRulesOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	if err := o.Data.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("getTcpRequestRulesOK" + "." + "data")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetTCPRequestRulesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTCPRequestRulesOKBody) UnmarshalBinary(b []byte) error {
	var res GetTCPRequestRulesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
