openapi: 3.0.1
info:
  title: HAProxy Data Plane API - Dgram Bind
  description: An API for managing HAProxy Dgram Bind entries.
servers:
  - url: /v3
components:
  schemas:
    dgram_bind:
      type: object
      x-go-type: models.DgramBind
      x-go-type-import:
        path: github.com/haproxytech/client-native/v6/models
    dgram_binds:
      type: array
      items:
        $ref: '#/components/schemas/dgram_bind'
      x-go-type: models.DgramBinds
      x-go-type-import:
        path: github.com/haproxytech/client-native/v6/models
paths:
  /services/haproxy/configuration/log_forwards/{parent_name}/dgram_binds:
    get:
      summary: Return an array of dgram binds
      description: Returns all dgram binds that are configured in specified log forward.
      operationId: getDgramBinds
      tags:
        - DgramBind
      parameters:
        - name: parent_name
          in: path
          description: Parent log forward name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dgram_binds'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
    post:
      summary: Add a new dgram bind
      description: Adds a new dgram bind in the specified log forward.
      operationId: createDgramBind
      tags:
        - DgramBind
      parameters:
        - name: parent_name
          in: path
          description: Parent log forward name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dgram_bind'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dgram_bind'
        '201':
          description: Dgram Bind created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dgram_bind'
        '409':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/AlreadyExists'
        '400':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
  /services/haproxy/configuration/log_forwards/{parent_name}/dgram_binds/{name}:
    get:
      summary: Return one dgram bind
      description: Returns one dgram bind configuration by its name in the specified log forward.
      operationId: getDgramBind
      tags:
        - DgramBind
      parameters:
        - name: name
          in: path
          description: Dgram Bind name
          required: true
          schema:
            type: string
        - name: parent_name
          in: path
          description: Parent log forward name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dgram_bind'
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
    put:
      summary: Replace a dgram bind
      description: Replaces a dgram bind configuration by its name in the specified log forward.
      operationId: replaceDgramBind
      tags:
        - DgramBind
      parameters:
        - name: name
          in: path
          description: Dgram Bind name
          required: true
          schema:
            type: string
        - name: parent_name
          in: path
          description: Parent log forward name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dgram_bind'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dgram_bind'
        '200':
          description: Dgram Bind replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dgram_bind'
        '400':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
    delete:
      summary: Delete a dgram bind
      description: Deletes a dgram bind configuration by its name from the specified log forward.
      operationId: deleteDgramBind
      tags:
        - DgramBind
      parameters:
        - name: name
          in: path
          description: Dgram Bind name
          required: true
          schema:
            type: string
        - name: parent_name
          in: path
          description: Parent log forward name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
        '204':
          description: Dgram Bind deleted
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
