// Package traces provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package traces

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/haproxytech/client-native/v6/models"
	"github.com/oapi-codegen/runtime"
)

// TraceEntry defines model for trace_entry.
type TraceEntry = models.TraceEntry

// Traces defines model for traces.
type Traces = models.Traces

// DeleteTracesParams defines parameters for DeleteTraces.
type DeleteTracesParams struct {
	// TransactionId ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	TransactionId string `form:"transaction_id,omitempty" json:"transaction_id,omitempty,omitzero"`

	// Version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
	Version int `form:"version,omitempty" json:"version,omitempty,omitzero"`

	// ForceReload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
	ForceReload bool `form:"force_reload,omitempty" json:"force_reload,omitempty,omitzero"`
}

// GetTracesParams defines parameters for GetTraces.
type GetTracesParams struct {
	// TransactionId ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	TransactionId string `form:"transaction_id,omitempty" json:"transaction_id,omitempty,omitzero"`

	// FullSection Indicates if the action affects the specified child resources as well
	FullSection bool `form:"full_section,omitempty" json:"full_section,omitempty,omitzero"`
}

// CreateTracesParams defines parameters for CreateTraces.
type CreateTracesParams struct {
	// TransactionId ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	TransactionId string `form:"transaction_id,omitempty" json:"transaction_id,omitempty,omitzero"`

	// Version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
	Version int `form:"version,omitempty" json:"version,omitempty,omitzero"`

	// ForceReload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
	ForceReload bool `form:"force_reload,omitempty" json:"force_reload,omitempty,omitzero"`
}

// ReplaceTracesParams defines parameters for ReplaceTraces.
type ReplaceTracesParams struct {
	// TransactionId ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	TransactionId string `form:"transaction_id,omitempty" json:"transaction_id,omitempty,omitzero"`

	// Version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
	Version int `form:"version,omitempty" json:"version,omitempty,omitzero"`

	// ForceReload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
	ForceReload bool `form:"force_reload,omitempty" json:"force_reload,omitempty,omitzero"`

	// FullSection Indicates if the action affects the specified child resources as well
	FullSection bool `form:"full_section,omitempty" json:"full_section,omitempty,omitzero"`
}

// DeleteTraceEntryParams defines parameters for DeleteTraceEntry.
type DeleteTraceEntryParams struct {
	// TransactionId ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	TransactionId string `form:"transaction_id,omitempty" json:"transaction_id,omitempty,omitzero"`

	// Version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
	Version int `form:"version,omitempty" json:"version,omitempty,omitzero"`

	// ForceReload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
	ForceReload bool `form:"force_reload,omitempty" json:"force_reload,omitempty,omitzero"`
}

// CreateTraceEntryParams defines parameters for CreateTraceEntry.
type CreateTraceEntryParams struct {
	// TransactionId ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	TransactionId string `form:"transaction_id,omitempty" json:"transaction_id,omitempty,omitzero"`

	// Version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
	Version int `form:"version,omitempty" json:"version,omitempty,omitzero"`

	// ForceReload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
	ForceReload bool `form:"force_reload,omitempty" json:"force_reload,omitempty,omitzero"`
}

// CreateTracesJSONRequestBody defines body for CreateTraces for application/json ContentType.
type CreateTracesJSONRequestBody = Traces

// ReplaceTracesJSONRequestBody defines body for ReplaceTraces for application/json ContentType.
type ReplaceTracesJSONRequestBody = Traces

// DeleteTraceEntryJSONRequestBody defines body for DeleteTraceEntry for application/json ContentType.
type DeleteTraceEntryJSONRequestBody = TraceEntry

// CreateTraceEntryJSONRequestBody defines body for CreateTraceEntry for application/json ContentType.
type CreateTraceEntryJSONRequestBody = TraceEntry

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delete the traces configuration
	// (DELETE /services/haproxy/configuration/traces)
	DeleteTraces(w http.ResponseWriter, r *http.Request, params DeleteTracesParams)
	// Return the traces configuration
	// (GET /services/haproxy/configuration/traces)
	GetTraces(w http.ResponseWriter, r *http.Request, params GetTracesParams)
	// Add a traces configuration
	// (POST /services/haproxy/configuration/traces)
	CreateTraces(w http.ResponseWriter, r *http.Request, params CreateTracesParams)
	// Replace the traces configuration
	// (PUT /services/haproxy/configuration/traces)
	ReplaceTraces(w http.ResponseWriter, r *http.Request, params ReplaceTracesParams)
	// Delete a trace entry
	// (DELETE /services/haproxy/configuration/traces/entries)
	DeleteTraceEntry(w http.ResponseWriter, r *http.Request, params DeleteTraceEntryParams)
	// Add a new trace entry
	// (POST /services/haproxy/configuration/traces/entries)
	CreateTraceEntry(w http.ResponseWriter, r *http.Request, params CreateTraceEntryParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Delete the traces configuration
// (DELETE /services/haproxy/configuration/traces)
func (_ Unimplemented) DeleteTraces(w http.ResponseWriter, r *http.Request, params DeleteTracesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return the traces configuration
// (GET /services/haproxy/configuration/traces)
func (_ Unimplemented) GetTraces(w http.ResponseWriter, r *http.Request, params GetTracesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a traces configuration
// (POST /services/haproxy/configuration/traces)
func (_ Unimplemented) CreateTraces(w http.ResponseWriter, r *http.Request, params CreateTracesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Replace the traces configuration
// (PUT /services/haproxy/configuration/traces)
func (_ Unimplemented) ReplaceTraces(w http.ResponseWriter, r *http.Request, params ReplaceTracesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a trace entry
// (DELETE /services/haproxy/configuration/traces/entries)
func (_ Unimplemented) DeleteTraceEntry(w http.ResponseWriter, r *http.Request, params DeleteTraceEntryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new trace entry
// (POST /services/haproxy/configuration/traces/entries)
func (_ Unimplemented) CreateTraceEntry(w http.ResponseWriter, r *http.Request, params CreateTraceEntryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteTraces operation middleware
func (siw *ServerInterfaceWrapper) DeleteTraces(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteTracesParams

	// ------------- Optional query parameter "transaction_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "transaction_id", r.URL.Query(), &params.TransactionId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "transaction_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transaction_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "version", r.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "version"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "force_reload" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force_reload", r.URL.Query(), &params.ForceReload, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force_reload"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force_reload", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTraces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTraces operation middleware
func (siw *ServerInterfaceWrapper) GetTraces(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTracesParams

	// ------------- Optional query parameter "transaction_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "transaction_id", r.URL.Query(), &params.TransactionId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "transaction_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transaction_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "full_section" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "full_section", r.URL.Query(), &params.FullSection, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "full_section"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "full_section", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTraces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTraces operation middleware
func (siw *ServerInterfaceWrapper) CreateTraces(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTracesParams

	// ------------- Optional query parameter "transaction_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "transaction_id", r.URL.Query(), &params.TransactionId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "transaction_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transaction_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "version", r.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "version"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "force_reload" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force_reload", r.URL.Query(), &params.ForceReload, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force_reload"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force_reload", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTraces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceTraces operation middleware
func (siw *ServerInterfaceWrapper) ReplaceTraces(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ReplaceTracesParams

	// ------------- Optional query parameter "transaction_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "transaction_id", r.URL.Query(), &params.TransactionId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "transaction_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transaction_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "version", r.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "version"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "force_reload" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force_reload", r.URL.Query(), &params.ForceReload, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force_reload"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force_reload", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "full_section" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "full_section", r.URL.Query(), &params.FullSection, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "full_section"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "full_section", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceTraces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTraceEntry operation middleware
func (siw *ServerInterfaceWrapper) DeleteTraceEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteTraceEntryParams

	// ------------- Optional query parameter "transaction_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "transaction_id", r.URL.Query(), &params.TransactionId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "transaction_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transaction_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "version", r.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "version"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "force_reload" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force_reload", r.URL.Query(), &params.ForceReload, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force_reload"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force_reload", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTraceEntry(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTraceEntry operation middleware
func (siw *ServerInterfaceWrapper) CreateTraceEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTraceEntryParams

	// ------------- Optional query parameter "transaction_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "transaction_id", r.URL.Query(), &params.TransactionId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "transaction_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transaction_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "version", r.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "version"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "force_reload" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force_reload", r.URL.Query(), &params.ForceReload, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force_reload"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force_reload", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTraceEntry(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/services/haproxy/configuration/traces", wrapper.DeleteTraces)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/services/haproxy/configuration/traces", wrapper.GetTraces)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/services/haproxy/configuration/traces", wrapper.CreateTraces)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/services/haproxy/configuration/traces", wrapper.ReplaceTraces)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/services/haproxy/configuration/traces/entries", wrapper.DeleteTraceEntry)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/services/haproxy/configuration/traces/entries", wrapper.CreateTraceEntry)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FlNb+M2E/4rBN/3KFtJNihQ35yPbn0pgjTopQgMhhxZ3FKklqTsGAv994KkZFuRnDpZOx+GbrZEDp8Z",
	"cp5nOPqBqcpyJUFag0c/sAaTK2nA/zE5UJ5wSixXcpopBsJMqcoyJaergfXzsdBA2PL6kZtgiippQVr3",
	"k+S5qMzE34yS3jhNISPu1/81JHiE/xevocThrYlfBAG0VhqXZRlhBoZqnrtZeITvUkCVJWBIg1GFpoBI",
	"gIwgYI5wCoSB9ugvlUz4rNB+4cFfoA0PuJuWG8NQwgWgeTU22nDRLnPAI2ys5nLmEJbRy6J7QdgtfC/A",
	"2A8W2gviAhqQfeQAXkFCCmGvvR8fK4RfQYImAgVsHzmIfyj7myok+xzpvSAGSWVR4iG/aVzL+vXLeRTq",
	"E1pZVQ/fgLrcehzM1KB6GMYO6xOzejXgWa6035Sc2BSP8IzbtHgYUpXFKcm1elxaoGlMBQdpB5JYPod4",
	"/kscLGKH3GpCYQrS6uWOOO7cjGs/4SBgzEtwmD1jcCi4TFT7eIwlGt9MUKI0yogkMy5n6PfxjbOJAhRE",
	"N0/QEEfYcisc4nrcFbEE3QgiwdsaoJUP9UkbYVxGWOUgSc7xCH8ZngxPceT98YGJDeg5p2Bqh+LGqvE6",
	"hAwEWGg7cuWfI5sCWqRKAApTkAFa41Y5BHMTtpqwgpoTTTKwPrn+fmp8coVU4m1bTaQh3iRapKABLVyW",
	"SousQoQxP2i10BBdEuny9wFQYYC5KbLOP8TNOuUdPu6W+l6AP4KSZC7GG+tNOXs2ZaOnqCtOCCu7HaYp",
	"0H/cDjeCW+PpBrvp8CbgqPEmJQZxa5BarM1t8egZ9uHSwgx0ly+TBBmwEWIKEecLBaRBKML8I4d6Qbj1",
	"XrodqB30XOqGDRgIsnypi8QgmhI5A4N4cxzR4Ff1ugEMMa6BWrF0x6CVMF1h8D5MA7hGLFhQeTxKiDAQ",
	"1bF5UEoAkbgs76NmiXt2cvZftB+cQIRSyC0wRGQdl7rwgSfqchuiNrlqm14nw2ou6vCjS6nPTs7b9rpo",
	"BoU0Z442zsOkLg1exSF+XQ3gZbgK915XaJRqXkqLLCNOjDaJynZ47viVzBwJVYHB92WEZ2DbgbsFW2i5",
	"aakiO1QVNqbNel/BHjPlTSRzO+TyNYCv0zVJgFrjH63LLJpysS62jEv3BQixLWMLIaZVhH82Y0/2Vn5W",
	"ythRUv5ZUArGJIVY785bl+ZHlrvtjNshd3NlOpL3UgNp0sDWSiUM7SuVvlL5jJWKLxEuFFsehPKcfa6B",
	"4ZHVBZQtoj19A6LtLGCoT1pPU1WBdmAUH7PiOw9St0d63mgjevu/7tl+swn8HiozZgyRXQUmwo8DqhjM",
	"QA6q3Rk8KLYcVNnLiCXOi7zorCBzQSg8V0K21Kia08tRL0efTI4+023hfVXz5L1UUwdy6WXz4LJ5ZPey",
	"lo7tRzfLaMfWdAzSar5Li9rU2o785wmUaJXtdA3caFjX3yl67e21t78KVt/5dlK2I2iVV7xx9B3yBk3+",
	"zM2ns/82ZswxsYRFg425tKqLjdFd+4q04EK4pKyu+q6IlAAs8OLWFl7P3T1399z9Gu4+PdzS22n2kH28",
	"7Qj6Zt5xNfOeyMzr7yPONuh5rRqFFniE4/kXXN6X/wYAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
