// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package http_check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/haproxytech/client-native/v6/models"
)

// ReplaceHTTPCheckHealthcheckOKCode is the HTTP code returned for type ReplaceHTTPCheckHealthcheckOK
const ReplaceHTTPCheckHealthcheckOKCode int = 200

/*
ReplaceHTTPCheckHealthcheckOK HTTP check replaced

swagger:response replaceHttpCheckHealthcheckOK
*/
type ReplaceHTTPCheckHealthcheckOK struct {

	/*
	  In: Body
	*/
	Payload *models.HTTPCheck `json:"body,omitempty"`
}

// NewReplaceHTTPCheckHealthcheckOK creates ReplaceHTTPCheckHealthcheckOK with default headers values
func NewReplaceHTTPCheckHealthcheckOK() *ReplaceHTTPCheckHealthcheckOK {

	return &ReplaceHTTPCheckHealthcheckOK{}
}

// WithPayload adds the payload to the replace Http check healthcheck o k response
func (o *ReplaceHTTPCheckHealthcheckOK) WithPayload(payload *models.HTTPCheck) *ReplaceHTTPCheckHealthcheckOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace Http check healthcheck o k response
func (o *ReplaceHTTPCheckHealthcheckOK) SetPayload(payload *models.HTTPCheck) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceHTTPCheckHealthcheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceHTTPCheckHealthcheckAcceptedCode is the HTTP code returned for type ReplaceHTTPCheckHealthcheckAccepted
const ReplaceHTTPCheckHealthcheckAcceptedCode int = 202

/*
ReplaceHTTPCheckHealthcheckAccepted Configuration change accepted and reload requested

swagger:response replaceHttpCheckHealthcheckAccepted
*/
type ReplaceHTTPCheckHealthcheckAccepted struct {
	/*ID of the requested reload

	 */
	ReloadID string `json:"Reload-ID"`

	/*
	  In: Body
	*/
	Payload *models.HTTPCheck `json:"body,omitempty"`
}

// NewReplaceHTTPCheckHealthcheckAccepted creates ReplaceHTTPCheckHealthcheckAccepted with default headers values
func NewReplaceHTTPCheckHealthcheckAccepted() *ReplaceHTTPCheckHealthcheckAccepted {

	return &ReplaceHTTPCheckHealthcheckAccepted{}
}

// WithReloadID adds the reloadId to the replace Http check healthcheck accepted response
func (o *ReplaceHTTPCheckHealthcheckAccepted) WithReloadID(reloadID string) *ReplaceHTTPCheckHealthcheckAccepted {
	o.ReloadID = reloadID
	return o
}

// SetReloadID sets the reloadId to the replace Http check healthcheck accepted response
func (o *ReplaceHTTPCheckHealthcheckAccepted) SetReloadID(reloadID string) {
	o.ReloadID = reloadID
}

// WithPayload adds the payload to the replace Http check healthcheck accepted response
func (o *ReplaceHTTPCheckHealthcheckAccepted) WithPayload(payload *models.HTTPCheck) *ReplaceHTTPCheckHealthcheckAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace Http check healthcheck accepted response
func (o *ReplaceHTTPCheckHealthcheckAccepted) SetPayload(payload *models.HTTPCheck) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceHTTPCheckHealthcheckAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Reload-ID

	reloadID := o.ReloadID
	if reloadID != "" {
		rw.Header().Set("Reload-ID", reloadID)
	}

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceHTTPCheckHealthcheckBadRequestCode is the HTTP code returned for type ReplaceHTTPCheckHealthcheckBadRequest
const ReplaceHTTPCheckHealthcheckBadRequestCode int = 400

/*
ReplaceHTTPCheckHealthcheckBadRequest Bad request

swagger:response replaceHttpCheckHealthcheckBadRequest
*/
type ReplaceHTTPCheckHealthcheckBadRequest struct {
	/*Configuration file version

	 */
	ConfigurationVersion string `json:"Configuration-Version"`

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReplaceHTTPCheckHealthcheckBadRequest creates ReplaceHTTPCheckHealthcheckBadRequest with default headers values
func NewReplaceHTTPCheckHealthcheckBadRequest() *ReplaceHTTPCheckHealthcheckBadRequest {

	return &ReplaceHTTPCheckHealthcheckBadRequest{}
}

// WithConfigurationVersion adds the configurationVersion to the replace Http check healthcheck bad request response
func (o *ReplaceHTTPCheckHealthcheckBadRequest) WithConfigurationVersion(configurationVersion string) *ReplaceHTTPCheckHealthcheckBadRequest {
	o.ConfigurationVersion = configurationVersion
	return o
}

// SetConfigurationVersion sets the configurationVersion to the replace Http check healthcheck bad request response
func (o *ReplaceHTTPCheckHealthcheckBadRequest) SetConfigurationVersion(configurationVersion string) {
	o.ConfigurationVersion = configurationVersion
}

// WithPayload adds the payload to the replace Http check healthcheck bad request response
func (o *ReplaceHTTPCheckHealthcheckBadRequest) WithPayload(payload *models.Error) *ReplaceHTTPCheckHealthcheckBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace Http check healthcheck bad request response
func (o *ReplaceHTTPCheckHealthcheckBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceHTTPCheckHealthcheckBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Configuration-Version

	configurationVersion := o.ConfigurationVersion
	if configurationVersion != "" {
		rw.Header().Set("Configuration-Version", configurationVersion)
	}

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceHTTPCheckHealthcheckNotFoundCode is the HTTP code returned for type ReplaceHTTPCheckHealthcheckNotFound
const ReplaceHTTPCheckHealthcheckNotFoundCode int = 404

/*
ReplaceHTTPCheckHealthcheckNotFound The specified resource was not found

swagger:response replaceHttpCheckHealthcheckNotFound
*/
type ReplaceHTTPCheckHealthcheckNotFound struct {
	/*Configuration file version

	 */
	ConfigurationVersion string `json:"Configuration-Version"`

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReplaceHTTPCheckHealthcheckNotFound creates ReplaceHTTPCheckHealthcheckNotFound with default headers values
func NewReplaceHTTPCheckHealthcheckNotFound() *ReplaceHTTPCheckHealthcheckNotFound {

	return &ReplaceHTTPCheckHealthcheckNotFound{}
}

// WithConfigurationVersion adds the configurationVersion to the replace Http check healthcheck not found response
func (o *ReplaceHTTPCheckHealthcheckNotFound) WithConfigurationVersion(configurationVersion string) *ReplaceHTTPCheckHealthcheckNotFound {
	o.ConfigurationVersion = configurationVersion
	return o
}

// SetConfigurationVersion sets the configurationVersion to the replace Http check healthcheck not found response
func (o *ReplaceHTTPCheckHealthcheckNotFound) SetConfigurationVersion(configurationVersion string) {
	o.ConfigurationVersion = configurationVersion
}

// WithPayload adds the payload to the replace Http check healthcheck not found response
func (o *ReplaceHTTPCheckHealthcheckNotFound) WithPayload(payload *models.Error) *ReplaceHTTPCheckHealthcheckNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace Http check healthcheck not found response
func (o *ReplaceHTTPCheckHealthcheckNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceHTTPCheckHealthcheckNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Configuration-Version

	configurationVersion := o.ConfigurationVersion
	if configurationVersion != "" {
		rw.Header().Set("Configuration-Version", configurationVersion)
	}

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
ReplaceHTTPCheckHealthcheckDefault General Error

swagger:response replaceHttpCheckHealthcheckDefault
*/
type ReplaceHTTPCheckHealthcheckDefault struct {
	_statusCode int
	/*Configuration file version

	 */
	ConfigurationVersion string `json:"Configuration-Version"`

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReplaceHTTPCheckHealthcheckDefault creates ReplaceHTTPCheckHealthcheckDefault with default headers values
func NewReplaceHTTPCheckHealthcheckDefault(code int) *ReplaceHTTPCheckHealthcheckDefault {
	if code <= 0 {
		code = 500
	}

	return &ReplaceHTTPCheckHealthcheckDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the replace HTTP check healthcheck default response
func (o *ReplaceHTTPCheckHealthcheckDefault) WithStatusCode(code int) *ReplaceHTTPCheckHealthcheckDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the replace HTTP check healthcheck default response
func (o *ReplaceHTTPCheckHealthcheckDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithConfigurationVersion adds the configurationVersion to the replace HTTP check healthcheck default response
func (o *ReplaceHTTPCheckHealthcheckDefault) WithConfigurationVersion(configurationVersion string) *ReplaceHTTPCheckHealthcheckDefault {
	o.ConfigurationVersion = configurationVersion
	return o
}

// SetConfigurationVersion sets the configurationVersion to the replace HTTP check healthcheck default response
func (o *ReplaceHTTPCheckHealthcheckDefault) SetConfigurationVersion(configurationVersion string) {
	o.ConfigurationVersion = configurationVersion
}

// WithPayload adds the payload to the replace HTTP check healthcheck default response
func (o *ReplaceHTTPCheckHealthcheckDefault) WithPayload(payload *models.Error) *ReplaceHTTPCheckHealthcheckDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace HTTP check healthcheck default response
func (o *ReplaceHTTPCheckHealthcheckDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceHTTPCheckHealthcheckDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Configuration-Version

	configurationVersion := o.ConfigurationVersion
	if configurationVersion != "" {
		rw.Header().Set("Configuration-Version", configurationVersion)
	}

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
