// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package tcp_check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/haproxytech/client-native/v6/models"
)

// ReplaceTCPCheckHealthcheckOKCode is the HTTP code returned for type ReplaceTCPCheckHealthcheckOK
const ReplaceTCPCheckHealthcheckOKCode int = 200

/*
ReplaceTCPCheckHealthcheckOK TCP check replaced

swagger:response replaceTcpCheckHealthcheckOK
*/
type ReplaceTCPCheckHealthcheckOK struct {

	/*
	  In: Body
	*/
	Payload *models.TCPCheck `json:"body,omitempty"`
}

// NewReplaceTCPCheckHealthcheckOK creates ReplaceTCPCheckHealthcheckOK with default headers values
func NewReplaceTCPCheckHealthcheckOK() *ReplaceTCPCheckHealthcheckOK {

	return &ReplaceTCPCheckHealthcheckOK{}
}

// WithPayload adds the payload to the replace Tcp check healthcheck o k response
func (o *ReplaceTCPCheckHealthcheckOK) WithPayload(payload *models.TCPCheck) *ReplaceTCPCheckHealthcheckOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace Tcp check healthcheck o k response
func (o *ReplaceTCPCheckHealthcheckOK) SetPayload(payload *models.TCPCheck) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceTCPCheckHealthcheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceTCPCheckHealthcheckAcceptedCode is the HTTP code returned for type ReplaceTCPCheckHealthcheckAccepted
const ReplaceTCPCheckHealthcheckAcceptedCode int = 202

/*
ReplaceTCPCheckHealthcheckAccepted Configuration change accepted and reload requested

swagger:response replaceTcpCheckHealthcheckAccepted
*/
type ReplaceTCPCheckHealthcheckAccepted struct {
	/*ID of the requested reload

	 */
	ReloadID string `json:"Reload-ID"`

	/*
	  In: Body
	*/
	Payload *models.TCPCheck `json:"body,omitempty"`
}

// NewReplaceTCPCheckHealthcheckAccepted creates ReplaceTCPCheckHealthcheckAccepted with default headers values
func NewReplaceTCPCheckHealthcheckAccepted() *ReplaceTCPCheckHealthcheckAccepted {

	return &ReplaceTCPCheckHealthcheckAccepted{}
}

// WithReloadID adds the reloadId to the replace Tcp check healthcheck accepted response
func (o *ReplaceTCPCheckHealthcheckAccepted) WithReloadID(reloadID string) *ReplaceTCPCheckHealthcheckAccepted {
	o.ReloadID = reloadID
	return o
}

// SetReloadID sets the reloadId to the replace Tcp check healthcheck accepted response
func (o *ReplaceTCPCheckHealthcheckAccepted) SetReloadID(reloadID string) {
	o.ReloadID = reloadID
}

// WithPayload adds the payload to the replace Tcp check healthcheck accepted response
func (o *ReplaceTCPCheckHealthcheckAccepted) WithPayload(payload *models.TCPCheck) *ReplaceTCPCheckHealthcheckAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace Tcp check healthcheck accepted response
func (o *ReplaceTCPCheckHealthcheckAccepted) SetPayload(payload *models.TCPCheck) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceTCPCheckHealthcheckAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Reload-ID

	reloadID := o.ReloadID
	if reloadID != "" {
		rw.Header().Set("Reload-ID", reloadID)
	}

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceTCPCheckHealthcheckBadRequestCode is the HTTP code returned for type ReplaceTCPCheckHealthcheckBadRequest
const ReplaceTCPCheckHealthcheckBadRequestCode int = 400

/*
ReplaceTCPCheckHealthcheckBadRequest Bad request

swagger:response replaceTcpCheckHealthcheckBadRequest
*/
type ReplaceTCPCheckHealthcheckBadRequest struct {
	/*Configuration file version

	 */
	ConfigurationVersion string `json:"Configuration-Version"`

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReplaceTCPCheckHealthcheckBadRequest creates ReplaceTCPCheckHealthcheckBadRequest with default headers values
func NewReplaceTCPCheckHealthcheckBadRequest() *ReplaceTCPCheckHealthcheckBadRequest {

	return &ReplaceTCPCheckHealthcheckBadRequest{}
}

// WithConfigurationVersion adds the configurationVersion to the replace Tcp check healthcheck bad request response
func (o *ReplaceTCPCheckHealthcheckBadRequest) WithConfigurationVersion(configurationVersion string) *ReplaceTCPCheckHealthcheckBadRequest {
	o.ConfigurationVersion = configurationVersion
	return o
}

// SetConfigurationVersion sets the configurationVersion to the replace Tcp check healthcheck bad request response
func (o *ReplaceTCPCheckHealthcheckBadRequest) SetConfigurationVersion(configurationVersion string) {
	o.ConfigurationVersion = configurationVersion
}

// WithPayload adds the payload to the replace Tcp check healthcheck bad request response
func (o *ReplaceTCPCheckHealthcheckBadRequest) WithPayload(payload *models.Error) *ReplaceTCPCheckHealthcheckBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace Tcp check healthcheck bad request response
func (o *ReplaceTCPCheckHealthcheckBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceTCPCheckHealthcheckBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Configuration-Version

	configurationVersion := o.ConfigurationVersion
	if configurationVersion != "" {
		rw.Header().Set("Configuration-Version", configurationVersion)
	}

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceTCPCheckHealthcheckNotFoundCode is the HTTP code returned for type ReplaceTCPCheckHealthcheckNotFound
const ReplaceTCPCheckHealthcheckNotFoundCode int = 404

/*
ReplaceTCPCheckHealthcheckNotFound The specified resource was not found

swagger:response replaceTcpCheckHealthcheckNotFound
*/
type ReplaceTCPCheckHealthcheckNotFound struct {
	/*Configuration file version

	 */
	ConfigurationVersion string `json:"Configuration-Version"`

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReplaceTCPCheckHealthcheckNotFound creates ReplaceTCPCheckHealthcheckNotFound with default headers values
func NewReplaceTCPCheckHealthcheckNotFound() *ReplaceTCPCheckHealthcheckNotFound {

	return &ReplaceTCPCheckHealthcheckNotFound{}
}

// WithConfigurationVersion adds the configurationVersion to the replace Tcp check healthcheck not found response
func (o *ReplaceTCPCheckHealthcheckNotFound) WithConfigurationVersion(configurationVersion string) *ReplaceTCPCheckHealthcheckNotFound {
	o.ConfigurationVersion = configurationVersion
	return o
}

// SetConfigurationVersion sets the configurationVersion to the replace Tcp check healthcheck not found response
func (o *ReplaceTCPCheckHealthcheckNotFound) SetConfigurationVersion(configurationVersion string) {
	o.ConfigurationVersion = configurationVersion
}

// WithPayload adds the payload to the replace Tcp check healthcheck not found response
func (o *ReplaceTCPCheckHealthcheckNotFound) WithPayload(payload *models.Error) *ReplaceTCPCheckHealthcheckNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace Tcp check healthcheck not found response
func (o *ReplaceTCPCheckHealthcheckNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceTCPCheckHealthcheckNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Configuration-Version

	configurationVersion := o.ConfigurationVersion
	if configurationVersion != "" {
		rw.Header().Set("Configuration-Version", configurationVersion)
	}

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
ReplaceTCPCheckHealthcheckDefault General Error

swagger:response replaceTcpCheckHealthcheckDefault
*/
type ReplaceTCPCheckHealthcheckDefault struct {
	_statusCode int
	/*Configuration file version

	 */
	ConfigurationVersion string `json:"Configuration-Version"`

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReplaceTCPCheckHealthcheckDefault creates ReplaceTCPCheckHealthcheckDefault with default headers values
func NewReplaceTCPCheckHealthcheckDefault(code int) *ReplaceTCPCheckHealthcheckDefault {
	if code <= 0 {
		code = 500
	}

	return &ReplaceTCPCheckHealthcheckDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the replace TCP check healthcheck default response
func (o *ReplaceTCPCheckHealthcheckDefault) WithStatusCode(code int) *ReplaceTCPCheckHealthcheckDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the replace TCP check healthcheck default response
func (o *ReplaceTCPCheckHealthcheckDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithConfigurationVersion adds the configurationVersion to the replace TCP check healthcheck default response
func (o *ReplaceTCPCheckHealthcheckDefault) WithConfigurationVersion(configurationVersion string) *ReplaceTCPCheckHealthcheckDefault {
	o.ConfigurationVersion = configurationVersion
	return o
}

// SetConfigurationVersion sets the configurationVersion to the replace TCP check healthcheck default response
func (o *ReplaceTCPCheckHealthcheckDefault) SetConfigurationVersion(configurationVersion string) {
	o.ConfigurationVersion = configurationVersion
}

// WithPayload adds the payload to the replace TCP check healthcheck default response
func (o *ReplaceTCPCheckHealthcheckDefault) WithPayload(payload *models.Error) *ReplaceTCPCheckHealthcheckDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace TCP check healthcheck default response
func (o *ReplaceTCPCheckHealthcheckDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceTCPCheckHealthcheckDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Configuration-Version

	configurationVersion := o.ConfigurationVersion
	if configurationVersion != "" {
		rw.Header().Set("Configuration-Version", configurationVersion)
	}

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
