// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/haproxytech/models"
)

// GetServersOKCode is the HTTP code returned for type GetServersOK
const GetServersOKCode int = 200

/*GetServersOK Successful operation

swagger:response getServersOK
*/
type GetServersOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetServersOKBody `json:"body,omitempty"`
}

// NewGetServersOK creates GetServersOK with default headers values
func NewGetServersOK() *GetServersOK {

	return &GetServersOK{}
}

// WithPayload adds the payload to the get servers o k response
func (o *GetServersOK) WithPayload(payload *models.GetServersOKBody) *GetServersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get servers o k response
func (o *GetServersOK) SetPayload(payload *models.GetServersOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetServersDefault General Error

swagger:response getServersDefault
*/
type GetServersDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetServersDefault creates GetServersDefault with default headers values
func NewGetServersDefault(code int) *GetServersDefault {
	if code <= 0 {
		code = 500
	}

	return &GetServersDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get servers default response
func (o *GetServersDefault) WithStatusCode(code int) *GetServersDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get servers default response
func (o *GetServersDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get servers default response
func (o *GetServersDefault) WithPayload(payload *models.Error) *GetServersDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get servers default response
func (o *GetServersDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServersDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
