openapi: 3.0.1
info:
  title: HAProxy Data Plane API - Filter
  description: An API for managing HAProxy Filter lines.
servers:
  - url: /v3
components:
  schemas:
    filter:
      type: object
      x-go-type: models.Filter
      x-go-type-import:
        path: github.com/haproxytech/client-native/v6/models
    filters:
      type: array
      items:
        $ref: '#/components/schemas/filter'
      x-go-type: models.Filters
      x-go-type-import:
        path: github.com/haproxytech/client-native/v6/models
paths:
{{ range parents }}
  /services/haproxy/configuration/{{ .PathParentType }}/{parent_name}/filters:
    get:
      summary: Return an array of all Filters
      description: Returns all Filters that are configured in specified {{ .ParentType }}.
      operationId: getAllFilter{{ .ParentType }}
      tags:
        - Filter
      parameters:
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/filters'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
    put:
      summary: Replace a Filter list
      description: Replaces a whole list of Filters with the list given in parameter for the specified {{ .ParentType }}.
      operationId: replaceAllFilter{{ .ParentType }}
      tags:
        - Filter
      parameters:
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/filters'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/filters'
        '200':
          description: All Filters replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/filters'
        '400':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
  /services/haproxy/configuration/{{ .PathParentType }}/{parent_name}/filters/{index}:
    get:
      summary: Return one Filter
      description: Returns one Filter configuration by its index in the specified {{ .ParentType }}.
      operationId: getFilter{{ .ParentType }}
      tags:
        - Filter
      parameters:
        - name: index
          in: path
          description: Filter Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/filter'
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
    post:
      summary: Add a new Filter
      description: Adds a new Filter of the specified type in the specified {{ .ParentType }}.
      operationId: createFilter{{ .ParentType }}
      tags:
        - Filter
      parameters:
        - name: index
          in: path
          description: Filter Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/filter'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/filter'
        '201':
          description: Filter created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/filter'
        '409':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/AlreadyExists'
        '400':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
    put:
      summary: Replace a Filter
      description: Replaces a Filter configuration by its index in the specified {{ .ParentType }}.
      operationId: replaceFilter{{ .ParentType }}
      tags:
        - Filter
      parameters:
        - name: index
          in: path
          description: Filter Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/filter'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/filter'
        '200':
          description: Filter replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/filter'
        '400':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
    delete:
      summary: Delete a Filter
      description: Deletes a Filter configuration by its index from the specified {{ .ParentType }}.
      operationId: deleteFilter{{ .ParentType }}
      tags:
        - Filter
      parameters:
        - name: index
          in: path
          description: Filter Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
        '204':
          description: Filter deleted
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
{{ end }}
