// Code generated by go-swagger; DO NOT EDIT.

package listener

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteListenerHandlerFunc turns a function with the right signature into a delete listener handler
type DeleteListenerHandlerFunc func(DeleteListenerParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteListenerHandlerFunc) Handle(params DeleteListenerParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteListenerHandler interface for that can handle valid delete listener params
type DeleteListenerHandler interface {
	Handle(DeleteListenerParams, interface{}) middleware.Responder
}

// NewDeleteListener creates a new http.Handler for the delete listener operation
func NewDeleteListener(ctx *middleware.Context, handler DeleteListenerHandler) *DeleteListener {
	return &DeleteListener{Context: ctx, Handler: handler}
}

/*DeleteListener swagger:route DELETE /services/haproxy/configuration/listeners/{name} Listener deleteListener

Delete a listener

Deletes a listener configuration by it's name in the specified frontend.

*/
type DeleteListener struct {
	Context *middleware.Context
	Handler DeleteListenerHandler
}

func (o *DeleteListener) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteListenerParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
