// Package capture provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package capture

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/haproxytech/client-native/v6/models"
	"github.com/oapi-codegen/runtime"
)

// Capture defines model for capture.
type Capture = models.Capture

// Captures defines model for captures.
type Captures = models.Captures

// GetDeclareCapturesParams defines parameters for GetDeclareCaptures.
type GetDeclareCapturesParams struct {
	// TransactionId ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	TransactionId string `form:"transaction_id,omitempty" json:"transaction_id,omitempty,omitzero"`
}

// ReplaceDeclareCapturesParams defines parameters for ReplaceDeclareCaptures.
type ReplaceDeclareCapturesParams struct {
	// TransactionId ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	TransactionId string `form:"transaction_id,omitempty" json:"transaction_id,omitempty,omitzero"`

	// Version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
	Version int `form:"version,omitempty" json:"version,omitempty,omitzero"`

	// ForceReload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
	ForceReload bool `form:"force_reload,omitempty" json:"force_reload,omitempty,omitzero"`
}

// DeleteDeclareCaptureParams defines parameters for DeleteDeclareCapture.
type DeleteDeclareCaptureParams struct {
	// TransactionId ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	TransactionId string `form:"transaction_id,omitempty" json:"transaction_id,omitempty,omitzero"`

	// Version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
	Version int `form:"version,omitempty" json:"version,omitempty,omitzero"`

	// ForceReload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
	ForceReload bool `form:"force_reload,omitempty" json:"force_reload,omitempty,omitzero"`
}

// GetDeclareCaptureParams defines parameters for GetDeclareCapture.
type GetDeclareCaptureParams struct {
	// TransactionId ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	TransactionId string `form:"transaction_id,omitempty" json:"transaction_id,omitempty,omitzero"`
}

// CreateDeclareCaptureParams defines parameters for CreateDeclareCapture.
type CreateDeclareCaptureParams struct {
	// TransactionId ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	TransactionId string `form:"transaction_id,omitempty" json:"transaction_id,omitempty,omitzero"`

	// Version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
	Version int `form:"version,omitempty" json:"version,omitempty,omitzero"`

	// ForceReload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
	ForceReload bool `form:"force_reload,omitempty" json:"force_reload,omitempty,omitzero"`
}

// ReplaceDeclareCaptureParams defines parameters for ReplaceDeclareCapture.
type ReplaceDeclareCaptureParams struct {
	// TransactionId ID of the transaction where we want to add the operation. Cannot be used when version is specified.
	TransactionId string `form:"transaction_id,omitempty" json:"transaction_id,omitempty,omitzero"`

	// Version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
	Version int `form:"version,omitempty" json:"version,omitempty,omitzero"`

	// ForceReload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
	ForceReload bool `form:"force_reload,omitempty" json:"force_reload,omitempty,omitzero"`
}

// ReplaceDeclareCapturesJSONRequestBody defines body for ReplaceDeclareCaptures for application/json ContentType.
type ReplaceDeclareCapturesJSONRequestBody = Captures

// CreateDeclareCaptureJSONRequestBody defines body for CreateDeclareCapture for application/json ContentType.
type CreateDeclareCaptureJSONRequestBody = Capture

// ReplaceDeclareCaptureJSONRequestBody defines body for ReplaceDeclareCapture for application/json ContentType.
type ReplaceDeclareCaptureJSONRequestBody = Capture

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Return an array of all Declare Captures
	// (GET /services/haproxy/configuration/frontends/{parent_name}/captures)
	GetDeclareCaptures(w http.ResponseWriter, r *http.Request, parentName string, params GetDeclareCapturesParams)
	// Replace a Declare Capture list
	// (PUT /services/haproxy/configuration/frontends/{parent_name}/captures)
	ReplaceDeclareCaptures(w http.ResponseWriter, r *http.Request, parentName string, params ReplaceDeclareCapturesParams)
	// Delete a Declare Capture
	// (DELETE /services/haproxy/configuration/frontends/{parent_name}/captures/{index})
	DeleteDeclareCapture(w http.ResponseWriter, r *http.Request, parentName string, index int, params DeleteDeclareCaptureParams)
	// Return one Declare Capture
	// (GET /services/haproxy/configuration/frontends/{parent_name}/captures/{index})
	GetDeclareCapture(w http.ResponseWriter, r *http.Request, parentName string, index int, params GetDeclareCaptureParams)
	// Add a new Declare Capture
	// (POST /services/haproxy/configuration/frontends/{parent_name}/captures/{index})
	CreateDeclareCapture(w http.ResponseWriter, r *http.Request, parentName string, index int, params CreateDeclareCaptureParams)
	// Replace a Declare Capture
	// (PUT /services/haproxy/configuration/frontends/{parent_name}/captures/{index})
	ReplaceDeclareCapture(w http.ResponseWriter, r *http.Request, parentName string, index int, params ReplaceDeclareCaptureParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Return an array of all Declare Captures
// (GET /services/haproxy/configuration/frontends/{parent_name}/captures)
func (_ Unimplemented) GetDeclareCaptures(w http.ResponseWriter, r *http.Request, parentName string, params GetDeclareCapturesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Replace a Declare Capture list
// (PUT /services/haproxy/configuration/frontends/{parent_name}/captures)
func (_ Unimplemented) ReplaceDeclareCaptures(w http.ResponseWriter, r *http.Request, parentName string, params ReplaceDeclareCapturesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a Declare Capture
// (DELETE /services/haproxy/configuration/frontends/{parent_name}/captures/{index})
func (_ Unimplemented) DeleteDeclareCapture(w http.ResponseWriter, r *http.Request, parentName string, index int, params DeleteDeclareCaptureParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return one Declare Capture
// (GET /services/haproxy/configuration/frontends/{parent_name}/captures/{index})
func (_ Unimplemented) GetDeclareCapture(w http.ResponseWriter, r *http.Request, parentName string, index int, params GetDeclareCaptureParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new Declare Capture
// (POST /services/haproxy/configuration/frontends/{parent_name}/captures/{index})
func (_ Unimplemented) CreateDeclareCapture(w http.ResponseWriter, r *http.Request, parentName string, index int, params CreateDeclareCaptureParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Replace a Declare Capture
// (PUT /services/haproxy/configuration/frontends/{parent_name}/captures/{index})
func (_ Unimplemented) ReplaceDeclareCapture(w http.ResponseWriter, r *http.Request, parentName string, index int, params ReplaceDeclareCaptureParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDeclareCaptures operation middleware
func (siw *ServerInterfaceWrapper) GetDeclareCaptures(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "parent_name" -------------
	var parentName string

	err = runtime.BindStyledParameterWithOptions("simple", "parent_name", chi.URLParam(r, "parent_name"), &parentName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "parent_name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDeclareCapturesParams

	// ------------- Optional query parameter "transaction_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "transaction_id", r.URL.Query(), &params.TransactionId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "transaction_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transaction_id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeclareCaptures(w, r, parentName, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceDeclareCaptures operation middleware
func (siw *ServerInterfaceWrapper) ReplaceDeclareCaptures(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "parent_name" -------------
	var parentName string

	err = runtime.BindStyledParameterWithOptions("simple", "parent_name", chi.URLParam(r, "parent_name"), &parentName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "parent_name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ReplaceDeclareCapturesParams

	// ------------- Optional query parameter "transaction_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "transaction_id", r.URL.Query(), &params.TransactionId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "transaction_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transaction_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "version", r.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "version"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "force_reload" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force_reload", r.URL.Query(), &params.ForceReload, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force_reload"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force_reload", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceDeclareCaptures(w, r, parentName, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDeclareCapture operation middleware
func (siw *ServerInterfaceWrapper) DeleteDeclareCapture(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "parent_name" -------------
	var parentName string

	err = runtime.BindStyledParameterWithOptions("simple", "parent_name", chi.URLParam(r, "parent_name"), &parentName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "parent_name", Err: err})
		return
	}

	// ------------- Path parameter "index" -------------
	var index int

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteDeclareCaptureParams

	// ------------- Optional query parameter "transaction_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "transaction_id", r.URL.Query(), &params.TransactionId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "transaction_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transaction_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "version", r.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "version"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "force_reload" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force_reload", r.URL.Query(), &params.ForceReload, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force_reload"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force_reload", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDeclareCapture(w, r, parentName, index, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeclareCapture operation middleware
func (siw *ServerInterfaceWrapper) GetDeclareCapture(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "parent_name" -------------
	var parentName string

	err = runtime.BindStyledParameterWithOptions("simple", "parent_name", chi.URLParam(r, "parent_name"), &parentName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "parent_name", Err: err})
		return
	}

	// ------------- Path parameter "index" -------------
	var index int

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDeclareCaptureParams

	// ------------- Optional query parameter "transaction_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "transaction_id", r.URL.Query(), &params.TransactionId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "transaction_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transaction_id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeclareCapture(w, r, parentName, index, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDeclareCapture operation middleware
func (siw *ServerInterfaceWrapper) CreateDeclareCapture(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "parent_name" -------------
	var parentName string

	err = runtime.BindStyledParameterWithOptions("simple", "parent_name", chi.URLParam(r, "parent_name"), &parentName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "parent_name", Err: err})
		return
	}

	// ------------- Path parameter "index" -------------
	var index int

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateDeclareCaptureParams

	// ------------- Optional query parameter "transaction_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "transaction_id", r.URL.Query(), &params.TransactionId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "transaction_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transaction_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "version", r.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "version"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "force_reload" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force_reload", r.URL.Query(), &params.ForceReload, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force_reload"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force_reload", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDeclareCapture(w, r, parentName, index, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceDeclareCapture operation middleware
func (siw *ServerInterfaceWrapper) ReplaceDeclareCapture(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "parent_name" -------------
	var parentName string

	err = runtime.BindStyledParameterWithOptions("simple", "parent_name", chi.URLParam(r, "parent_name"), &parentName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "parent_name", Err: err})
		return
	}

	// ------------- Path parameter "index" -------------
	var index int

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ReplaceDeclareCaptureParams

	// ------------- Optional query parameter "transaction_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "transaction_id", r.URL.Query(), &params.TransactionId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "transaction_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transaction_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "version", r.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "version"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "force_reload" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force_reload", r.URL.Query(), &params.ForceReload, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force_reload"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force_reload", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceDeclareCapture(w, r, parentName, index, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/services/haproxy/configuration/frontends/{parent_name}/captures", wrapper.GetDeclareCaptures)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/services/haproxy/configuration/frontends/{parent_name}/captures", wrapper.ReplaceDeclareCaptures)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/services/haproxy/configuration/frontends/{parent_name}/captures/{index}", wrapper.DeleteDeclareCapture)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/services/haproxy/configuration/frontends/{parent_name}/captures/{index}", wrapper.GetDeclareCapture)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/services/haproxy/configuration/frontends/{parent_name}/captures/{index}", wrapper.CreateDeclareCapture)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/services/haproxy/configuration/frontends/{parent_name}/captures/{index}", wrapper.ReplaceDeclareCapture)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Frfb9s2EP5XCLZPm2y5aVBg3pObdFtehqAb9tKkwYU8W+wkUiUpO0ag/30gKclSrMRxm18r9FI4EnX8",
	"7nj3fadTrylTWa4kSmvo9JpqNLmSBv0fJkcm5oKBFUpeZIpjai6YyjIlL5qF9fVZqhH4+sOVMMEUU9Ki",
	"tO4n5HlamYm/GCW9cZZgBu7Xa41zOqWv4g2UONw18V4QUGulaVmWEeVomBa5e4pO6d8JksoScqLRqEIz",
	"JBAgEwyYI5ogcNQe/ZGSc7EotN949A9qIwLuruXOMjIXKZJltTZquWjXOdIpNVYLuXAIy2i/6L4H/hG/",
	"FmjsCwvte3ABDchecgCPcQ5Faj94P15WCH9HiRpSErC95CD+qexvqpD8/1HeKzBEKkvmHvKTxrWsbwcm",
	"hNwWGltL1eUXZK5grkYLNaouBjfHR9Xq1s2RyHKlfaxzsAmd0oWwSXE5ZiqLE8i1ulpbZEnMUoHSjiRY",
	"scR4+S4ONqkDVKHwiITFzOw6nBp2GdWwQWtY34naPDjsb0iR+8W5LreHhOsACzlX26k0k2R2ekLmSpMM",
	"JCyEXJA/ZqfOJjlGloJGUsWQoLRaoBnTiFphU4e5WQoWyGkKEr25EdlkS52ZU+pOTOUoIRd0St+OJ+M3",
	"NPI++TOPDeqlYGhqp2LWzvN4rn1pcxNf56BR2gsJGZZxO4EWaLd9/Ii20NIQSNObPhliE7DEXak3Q06E",
	"bNVtva1zW+UYwJxwT5C2MtfKshw0ZGh9QX+6ieTU425MEucAdUdDp+FsI+ovub8aD2lEnZIJjZxOrS6w",
	"XeM5WIvaPf/50+ezM312Js+KyeQt8//iT7++fuV+Hby7Ls/o+c+vabRFC9FNlCfHRM2JTZBYDdIA8zSz",
	"SlAjWTn+kpZYRYBzv6gJypgcgXTMdomkMMjdI7JmJiLMJqjj2umvBer1xuvWfheC30lm51G3KTyYTB6M",
	"/puM6iH1vwrG0Jh5kW4cf2px5KFpuM2NJi7xt7cinuKKLAO9biqIgCSeal169BWTSy5YuMSn3cKg52VE",
	"86K3NvMUGBoCZJWoFEkqjHX2twp1JWzi882vWIglSleoTb15DrMdyb29dKtth/J9rvLdQl3VSdjZHSVL",
	"kP3r5KijAjWefrBth9uAo86dBAwR1hC12pi7xaM7KlJIiwvUvScwJwZtRLgi4HxhSDSmCri/5FCvQNgm",
	"YVvKE5aNOKaw3tdFMIQlIBdoXF2017k6coY8IyInXGhkNl27NOhE97YweB8uArhOLBommkNqsEnOS6VS",
	"BFnTtH8Ne6/4+pEYultf5TMpw6yvvdCBaLjrfQ4mB08CpKssIScIMIa5RU5A1mlWvyDjjbeQjyEJT463",
	"6XrDLc2zpCct+kTrMBzDAwpWa/jwPKLoj5bAVqPsFOoOLXS9PVMcFyhHVRhHl4qvR1W1cbDg9/rejji+",
	"FpLjVRnOMUWL2yd67K+bHi+6vHu59pzpDToFzO6ttWGHG0HYobQ1hhO3Xb/EiurW7eK6m6gHQR8EfRD0",
	"/QW9o64Hu95tXooCHUwO+/ivy3qBJ71eH4b1D6gmzaDyOfQq8PA20d/91nbnREVJ3Ec2XBbfUzS2ZiuD",
	"YgwTnL3b45c6wPnBmKUaD/WwwY6JkDI95DLj3LWjEldb3LIHgRxphKHrHLrOoescxkj3k4ldU6Q3T6FO",
	"W92Up7HHGh8N06N6enQ4+eWB7Xf/49FzyPKM834d/e7Z1O6POY/zVtD72WZQ9UHVB1UfVP3bVH3yHKr+",
	"yF+FBlnfyPoP9qJ9yyen7//a5PZBvawltNApndJ4+ZaW5+V/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
