openapi: 3.0.1
info:
  title: HAProxy Data Plane API - Stick Rule
  description: An API for managing HAProxy Stick Rule entries.
servers:
  - url: /v3
components:
  schemas:
    stick_rule:
      type: object
      x-go-type: models.StickRule
      x-go-type-import:
        path: github.com/haproxytech/client-native/v6/models
    stick_rules:
      type: array
      items:
        $ref: '#/components/schemas/stick_rule'
      x-go-type: models.StickRules
      x-go-type-import:
        path: github.com/haproxytech/client-native/v6/models
paths:
  /services/haproxy/configuration/backends/{parent_name}/stick_rules:
    get:
      summary: Return an array of all Stick Rules
      description: Returns all Stick Rules that are configured in specified backend.
      operationId: getStickRules
      tags:
        - StickRule
      parameters:
        - name: parent_name
          in: path
          description: Parent backend name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stick_rules'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
    put:
      summary: Replace a Stick Rule list
      description: Replaces a whole list of Stick Rules with the list given in parameter for the specified backend.
      operationId: replaceStickRules
      tags:
        - StickRule
      parameters:
        - name: parent_name
          in: path
          description: Parent backend name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stick_rules'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stick_rules'
        '200':
          description: All Stick Rules replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stick_rules'
        '400':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
  /services/haproxy/configuration/backends/{parent_name}/stick_rules/{index}:
    get:
      summary: Return one Stick Rule
      description: Returns one Stick Rule configuration by its index in the specified backend.
      operationId: getStickRule
      tags:
        - StickRule
      parameters:
        - name: index
          in: path
          description: Stick Rule Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent backend name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stick_rule'
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
    post:
      summary: Add a new Stick Rule
      description: Adds a new Stick Rule in the specified backend.
      operationId: createStickRule
      tags:
        - StickRule
      parameters:
        - name: index
          in: path
          description: Stick Rule Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent backend name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stick_rule'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stick_rule'
        '201':
          description: Stick Rule created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stick_rule'
        '409':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/AlreadyExists'
        '400':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
    put:
      summary: Replace a Stick Rule
      description: Replaces a Stick Rule configuration by its index in the specified backend.
      operationId: replaceStickRule
      tags:
        - StickRule
      parameters:
        - name: index
          in: path
          description: Stick Rule Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent backend name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stick_rule'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stick_rule'
        '200':
          description: Stick Rule replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stick_rule'
        '400':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
    delete:
      summary: Delete a Stick Rule
      description: Deletes a Stick Rule configuration by its index from the specified backend.
      operationId: deleteStickRule
      tags:
        - StickRule
      parameters:
        - name: index
          in: path
          description: Stick Rule Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent backend name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
        '204':
          description: Stick Rule deleted
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
