// Code generated by go-swagger; DO NOT EDIT.

package sites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateSiteHandlerFunc turns a function with the right signature into a create site handler
type CreateSiteHandlerFunc func(CreateSiteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateSiteHandlerFunc) Handle(params CreateSiteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateSiteHandler interface for that can handle valid create site params
type CreateSiteHandler interface {
	Handle(CreateSiteParams, interface{}) middleware.Responder
}

// NewCreateSite creates a new http.Handler for the create site operation
func NewCreateSite(ctx *middleware.Context, handler CreateSiteHandler) *CreateSite {
	return &CreateSite{Context: ctx, Handler: handler}
}

/*CreateSite swagger:route POST /services/haproxy/sites Sites createSite

Add a site

Adds a new site to the configuration file.

*/
type CreateSite struct {
	Context *middleware.Context
	Handler CreateSiteHandler
}

func (o *CreateSite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateSiteParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
