// Code generated by go-swagger; DO NOT EDIT.

package sites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetSiteHandlerFunc turns a function with the right signature into a get site handler
type GetSiteHandlerFunc func(GetSiteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSiteHandlerFunc) Handle(params GetSiteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetSiteHandler interface for that can handle valid get site params
type GetSiteHandler interface {
	Handle(GetSiteParams, interface{}) middleware.Responder
}

// NewGetSite creates a new http.Handler for the get site operation
func NewGetSite(ctx *middleware.Context, handler GetSiteHandler) *GetSite {
	return &GetSite{Context: ctx, Handler: handler}
}

/*GetSite swagger:route GET /services/haproxy/sites/{name} Sites getSite

Return a site

Returns one site configuration by it's name.

*/
type GetSite struct {
	Context *middleware.Context
	Handler GetSiteHandler
}

func (o *GetSite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSiteParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
