openapi: 3.0.1
info:
  title: HAProxy Data Plane API - Resolver
  description: An API for managing HAProxy resolver and nameserver configurations.
servers:
  - url: /v3
components:
  schemas:
    resolver:
      type: object
      x-go-type: models.Resolver
      x-go-type-import:
        path: github.com/haproxytech/client-native/v6/models
    resolvers:
      type: array
      items:
        $ref: '#/components/schemas/resolver'
      x-go-type: models.Resolvers
      x-go-type-import:
        path: github.com/haproxytech/client-native/v6/models
    nameserver:
      type: object
      x-go-type: models.Nameserver
      x-go-type-import:
        path: github.com/haproxytech/client-native/v6/models
    nameservers:
      type: array
      items:
        $ref: '#/components/schemas/nameserver'
      x-go-type: models.Nameservers
      x-go-type-import:
        path: github.com/haproxytech/client-native/v6/models
paths:
  /services/haproxy/configuration/resolvers:
    get:
      summary: Return an array of resolvers
      description: Returns an array of all configured resolvers.
      operationId: getResolvers
      tags:
        - Resolver
      parameters:
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: full_section
          in: query
          description: Indicates if the action affects the specified child resources as well
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resolvers'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
    post:
      summary: Add a resolver
      description: Adds a new resolver to the configuration file.
      operationId: createResolver
      tags:
        - Resolver
      parameters:
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
        - name: full_section
          in: query
          description: Indicates if the action affects the specified child resources as well
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/resolver'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resolver'
        '201':
          description: Resolver created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resolver'
        '409':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/AlreadyExists'
        '400':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data

  /services/haproxy/configuration/resolvers/{name}:
    get:
      summary: Return a resolver
      description: Returns one resolver configuration by its name.
      operationId: getResolver
      tags:
        - Resolver
      parameters:
        - name: name
          in: path
          description: Resolver name
          required: true
          schema:
            type: string
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: full_section
          in: query
          description: Indicates if the action affects the specified child resources as well
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resolver'
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
    put:
      summary: Replace a resolver
      description: Replaces a resolver configuration by its name.
      operationId: replaceResolver
      tags:
        - Resolver
      parameters:
        - name: name
          in: path
          description: Resolver name
          required: true
          schema:
            type: string
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
        - name: full_section
          in: query
          description: Indicates if the action affects the specified child resources as well
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/resolver'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resolver'
        '200':
          description: Resolver replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resolver'
        '400':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
    delete:
      summary: Delete a resolver
      description: Deletes a resolver from the configuration by its name.
      operationId: deleteResolver
      tags:
        - Resolver
      parameters:
        - name: name
          in: path
          description: Resolver name
          required: true
          schema:
            type: string
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
        '204':
          description: Resolver deleted
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'

  /services/haproxy/configuration/nameservers:
    get:
      summary: Return an array of nameservers
      description: Returns an array of all nameservers belonging to the specified resolver.
      operationId: getNameservers
      tags:
        - Nameserver
      parameters:
        - name: resolver
          in: query
          description: Parent resolver name
          required: true
          schema:
            type: string
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nameservers'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
    post:
      summary: Add a nameserver
      description: Adds a new nameserver to the specified resolver.
      operationId: createNameserver
      tags:
        - Nameserver
      parameters:
        - name: resolver
          in: query
          description: Parent resolver name
          required: true
          schema:
            type: string
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/nameserver'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nameserver'
        '201':
          description: Nameserver created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nameserver'
        '409':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/AlreadyExists'
        '400':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data

  /services/haproxy/configuration/nameservers/{name}:
    get:
      summary: Return a nameserver
      description: Returns one nameserver from the specified resolver by name.
      operationId: getNameserver
      tags:
        - Nameserver
      parameters:
        - name: name
          in: path
          description: Nameserver name
          required: true
          schema:
            type: string
        - name: resolver
          in: query
          description: Parent resolver name
          required: true
          schema:
            type: string
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nameserver'
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
    put:
      summary: Replace a nameserver
      description: Replaces a nameserver in the specified resolver by name.
      operationId: replaceNameserver
      tags:
        - Nameserver
      parameters:
        - name: name
          in: path
          description: Nameserver name
          required: true
          schema:
            type: string
        - name: resolver
          in: query
          description: Parent resolver name
          required: true
          schema:
            type: string
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/nameserver'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nameserver'
        '200':
          description: Nameserver replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nameserver'
        '400':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
    delete:
      summary: Delete a nameserver
      description: Deletes a nameserver from the specified resolver by name.
      operationId: deleteNameserver
      tags:
        - Nameserver
      parameters:
        - name: name
          in: path
          description: Nameserver name
          required: true
          schema:
            type: string
        - name: resolver
          in: query
          description: Parent resolver name
          required: true
          schema:
            type: string
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
        '204':
          description: Nameserver deleted
        '404':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../models/common/responses/models.yaml#/components/responses/DefaultError'
