// Code generated by go-swagger; DO NOT EDIT.

package stick_response_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetStickResponseRuleHandlerFunc turns a function with the right signature into a get stick response rule handler
type GetStickResponseRuleHandlerFunc func(GetStickResponseRuleParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetStickResponseRuleHandlerFunc) Handle(params GetStickResponseRuleParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetStickResponseRuleHandler interface for that can handle valid get stick response rule params
type GetStickResponseRuleHandler interface {
	Handle(GetStickResponseRuleParams, interface{}) middleware.Responder
}

// NewGetStickResponseRule creates a new http.Handler for the get stick response rule operation
func NewGetStickResponseRule(ctx *middleware.Context, handler GetStickResponseRuleHandler) *GetStickResponseRule {
	return &GetStickResponseRule{Context: ctx, Handler: handler}
}

/*GetStickResponseRule swagger:route GET /services/haproxy/configuration/stick_response_rules/{id} StickResponseRule getStickResponseRule

Return one Stick Response Rule

Returns one Stick Response Rule configuration by it's ID in the specified backend.

*/
type GetStickResponseRule struct {
	Context *middleware.Context
	Handler GetStickResponseRuleHandler
}

func (o *GetStickResponseRule) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetStickResponseRuleParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
