// Package maps provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package maps

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/haproxytech/client-native/v6/models"
	"github.com/oapi-codegen/runtime"
)

// Map defines model for map.
type Map = models.Map

// MapEntries defines model for map_entries.
type MapEntries = models.MapEntries

// MapEntry defines model for map_entry.
type MapEntry = models.MapEntry

// Maps defines model for maps.
type Maps = models.Maps

// GetAllRuntimeMapFilesParams defines parameters for GetAllRuntimeMapFiles.
type GetAllRuntimeMapFilesParams struct {
	// IncludeUnmanaged If true, also show unmanaged map files loaded in haproxy
	IncludeUnmanaged bool `form:"include_unmanaged,omitempty" json:"include_unmanaged,omitempty,omitzero"`
}

// ClearRuntimeMapParams defines parameters for ClearRuntimeMap.
type ClearRuntimeMapParams struct {
	// ForceDelete If true, deletes file from disk
	ForceDelete bool `form:"forceDelete,omitempty" json:"forceDelete,omitempty,omitzero"`

	// ForceSync If true, immediately syncs changes to disk
	ForceSync bool `form:"force_sync,omitempty" json:"force_sync,omitempty,omitzero"`
}

// AddPayloadRuntimeMapParams defines parameters for AddPayloadRuntimeMap.
type AddPayloadRuntimeMapParams struct {
	// ForceSync If true, immediately syncs changes to disk
	ForceSync bool `form:"force_sync,omitempty" json:"force_sync,omitempty,omitzero"`
}

// AddPayloadRuntimeMapJSONRequestBody defines body for AddPayloadRuntimeMap for application/json ContentType.
type AddPayloadRuntimeMapJSONRequestBody = MapEntries

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Return runtime map files
	// (GET /services/haproxy/runtime/maps)
	GetAllRuntimeMapFiles(w http.ResponseWriter, r *http.Request, params GetAllRuntimeMapFilesParams)
	// Remove all map entries from the map file
	// (DELETE /services/haproxy/runtime/maps/{name})
	ClearRuntimeMap(w http.ResponseWriter, r *http.Request, name string, params ClearRuntimeMapParams)
	// Return one runtime map file
	// (GET /services/haproxy/runtime/maps/{name})
	GetOneRuntimeMap(w http.ResponseWriter, r *http.Request, name string)
	// Add a new map payload
	// (PUT /services/haproxy/runtime/maps/{name})
	AddPayloadRuntimeMap(w http.ResponseWriter, r *http.Request, name string, params AddPayloadRuntimeMapParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Return runtime map files
// (GET /services/haproxy/runtime/maps)
func (_ Unimplemented) GetAllRuntimeMapFiles(w http.ResponseWriter, r *http.Request, params GetAllRuntimeMapFilesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove all map entries from the map file
// (DELETE /services/haproxy/runtime/maps/{name})
func (_ Unimplemented) ClearRuntimeMap(w http.ResponseWriter, r *http.Request, name string, params ClearRuntimeMapParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return one runtime map file
// (GET /services/haproxy/runtime/maps/{name})
func (_ Unimplemented) GetOneRuntimeMap(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new map payload
// (PUT /services/haproxy/runtime/maps/{name})
func (_ Unimplemented) AddPayloadRuntimeMap(w http.ResponseWriter, r *http.Request, name string, params AddPayloadRuntimeMapParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAllRuntimeMapFiles operation middleware
func (siw *ServerInterfaceWrapper) GetAllRuntimeMapFiles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllRuntimeMapFilesParams

	// ------------- Optional query parameter "include_unmanaged" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "include_unmanaged", r.URL.Query(), &params.IncludeUnmanaged, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "include_unmanaged"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_unmanaged", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllRuntimeMapFiles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClearRuntimeMap operation middleware
func (siw *ServerInterfaceWrapper) ClearRuntimeMap(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ClearRuntimeMapParams

	// ------------- Optional query parameter "forceDelete" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "forceDelete", r.URL.Query(), &params.ForceDelete, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "forceDelete"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "forceDelete", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "force_sync" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force_sync", r.URL.Query(), &params.ForceSync, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force_sync"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force_sync", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearRuntimeMap(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOneRuntimeMap operation middleware
func (siw *ServerInterfaceWrapper) GetOneRuntimeMap(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOneRuntimeMap(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddPayloadRuntimeMap operation middleware
func (siw *ServerInterfaceWrapper) AddPayloadRuntimeMap(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params AddPayloadRuntimeMapParams

	// ------------- Optional query parameter "force_sync" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force_sync", r.URL.Query(), &params.ForceSync, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force_sync"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force_sync", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddPayloadRuntimeMap(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/services/haproxy/runtime/maps", wrapper.GetAllRuntimeMapFiles)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/services/haproxy/runtime/maps/{name}", wrapper.ClearRuntimeMap)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/services/haproxy/runtime/maps/{name}", wrapper.GetOneRuntimeMap)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/services/haproxy/runtime/maps/{name}", wrapper.AddPayloadRuntimeMap)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FhNc9s2EP0rGMSnljKV2JMDe5Jjp/XBrcft9BI5mjWwlJDiKwAoh+Phf+8AJGUrlGI7lRs304uHFrC7",
	"Dw/vLUDeUGaUNRp18LS4oQ69Ndpj+sdbZKIUDIIweqYMR+lnzChl9Gw1sf/9CPgFfqzQhxjKjA6o0yNY",
	"K7sc+QdvdMrMFqggPu05LGlBX+S3OPJ21OePqo/OGUebpskoR8+csDGKFvQIOHEdsowuEDi6tLw3Rpdi",
	"XrmUfvQnOi9adOvxa9NIKSSSZTc3u7OQUFukBfXBCT2POJrscQQeYwmVDCdpHc+Lwp9RowNJWmzPmcRf",
	"TXhrKs2fGYF/LJB0mTCq0ZvKMSTX4Ik2gZQJ8r/Ka9MPp2oK7J1p5uoDsmiWT6O5GXU/tkvcPwN7d2Ak",
	"lDUucWwhLGhB5yIsqqt9ZlS+AOvMpzogW+RMCtRhpCGIJebL13mbj0YgCuwMdXCibTsioPL37UsfU9Mm",
	"63GDc1BvhX3SVXgq9PXDGTxJ058AyKP4ezBzu+fsK1z1MHL7DrVLuBGw0KVJEESQsdwvk/MYSY4hADmX",
	"oJFMzk/JiFxUOgiFpKOtN2NBI9vGogYraEEP9sf7L2mWMKW9yj26pWDoe1C5azPl/bbOMQz9f4GhctqT",
	"bjJRYFMX8Ps0lWsbwylPTTxMpOzwnYF9G6clCA4UhtR33n2e/7QkwVWYEZDeEL8w16TSCjTMkd8WI9IA",
	"R06EJh16GimjBf1YYVK6BhVpE5rJiuNslWOtS/H2BKRFCdLjSpxXxkgETZvmMlu/oLwaj3fW6BPNG1r3",
	"7xVj6H1ZSbLiM+7l4fhwW8oVxvzrzq6EoaNipxXWrhjJh5VSEDtXJ6ShjmhGA8yjNGiS9GUM+7JY85u4",
	"2027oxIDbpKtMkskIGWq1DV/UjqjSFjclh+q+I1EcLcivk+/Z10ikgTYiTI1gpUmu5F4RRQOOS2S4O+o",
	"xkII6GLg+3fvp1M3neppNR4fsPQXf/hp70V8evX6ppnSyx/3aDY4b7OtvmoZ8i3ItH4u/F9b7FMax/C4",
	"5XTD8X5rlO31hFLIBQSUNfG1Zp6wBeg5ehLMvaVnMeKfWvZwKIfJZzpoSeHfpc0eJvyh7bIvHwBG48C8",
	"G8+A3zT+5+zzxH3//7a/ST2bJGirDRKccO4JEI3XKdZCHa8DQ/FNOD9vx76j/v1N+mn6mHFkeL1LF6xe",
	"wZIb1ulsBgZ8+XSlhwroJEWA8/5UGO/YI3c+X30LH044H1po4MD4XsMMxznqUaeC0ZXh9agTFYcALYfx",
	"gtY7qnKSFjRfHtDmsvk7AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
