openapi: 3.0.1
info:
  title: HAProxy Data Plane API - QUIC Initial Rule
  description: An API for managing HAProxy QUIC Initial Rules.
servers:
  - url: /v3
components:
  schemas:
    quic_initial_rule:
      type: object
      x-go-type: models.QUICInitialRule
      x-go-type-import:
        path: github.com/haproxytech/client-native/v6/models
    quic_initial_rules:
      type: array
      items:
        $ref: '#/components/schemas/quic_initial_rule'
      x-go-type: models.QUICInitialRules
      x-go-type-import:
        path: github.com/haproxytech/client-native/v6/models
paths:
{{ range parents }}
  /services/haproxy/configuration/{{ .PathParentType }}/{parent_name}/quic_initial_rules:
    get:
      summary: Return an array of all QUIC Initial Rules
      description: Returns all QUIC Initial Rules that are configured in specified {{ .ParentType }}.
      operationId: getAllQUICInitialRule{{ .ParentType }}
      tags:
        - QUICInitialRule
      parameters:
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rules'
        'default':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/DefaultError'
    put:
      summary: Replace a QUIC Initial Rule list
      description: Replaces a whole list of QUIC Initial Rules with the list given in parameter for the specified {{ .ParentType }}.
      operationId: replaceAllQUICInitialRule{{ .ParentType }}
      tags:
        - QUICInitialRule
      parameters:
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quic_initial_rules'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rules'
        '200':
          description: All QUIC Initial Rules replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rules'
        '400':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        'default':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
  /services/haproxy/configuration/{{ .PathParentType }}/{parent_name}/quic_initial_rules/{index}:
    get:
      summary: Return one QUIC Initial Rule
      description: Returns one QUIC Initial Rule configuration by its index in the specified {{ .ParentType }}.
      operationId: getQUICInitialRule{{ .ParentType }}
      tags:
        - QUICInitialRule
      parameters:
        - name: index
          in: path
          description: QUIC Initial Rule Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '404':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/DefaultError'
    post:
      summary: Add a new QUIC Initial Rule
      description: Adds a new QUIC Initial Rule of the specified type in the specified {{ .ParentType }}.
      operationId: createQUICInitialRule{{ .ParentType }}
      tags:
        - QUICInitialRule
      parameters:
        - name: index
          in: path
          description: QUIC Initial Rule Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quic_initial_rule'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '201':
          description: QUIC Initial Rule created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '409':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/AlreadyExists'
        '400':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        'default':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
    put:
      summary: Replace a QUIC Initial Rule
      description: Replaces a QUIC Initial Rule configuration by its index in the specified {{ .ParentType }}.
      operationId: replaceQUICInitialRule{{ .ParentType }}
      tags:
        - QUICInitialRule
      parameters:
        - name: index
          in: path
          description: QUIC Initial Rule Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quic_initial_rule'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '200':
          description: QUIC Initial Rule replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '400':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        '404':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
    delete:
      summary: Delete a QUIC Initial Rule
      description: Deletes a QUIC Initial Rule configuration by its index from the specified {{ .ParentType }}.
      operationId: deleteQUICInitialRule{{ .ParentType }}
      tags:
        - QUICInitialRule
      parameters:
        - name: index
          in: path
          description: QUIC Initial Rule Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
        '204':
          description: QUIC Initial Rule deleted
        '404':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/DefaultError'
{{ end }}
