openapi: 3.0.1
info:
  title: HAProxy Data Plane API - TCP Check
  description: An API for managing HAProxy TCP Checks.
servers:
  - url: /v3
components:
  schemas:
    tcp_check:
      type: object
      x-go-type: models.TCPCheck
      x-go-type-import:
        path: github.com/haproxytech/client-native/v6/models
    tcp_checks:
      type: array
      items:
        $ref: '#/components/schemas/tcp_check'
      x-go-type: models.TCPChecks
      x-go-type-import:
        path: github.com/haproxytech/client-native/v6/models
paths:
{{ range parents }}
  /services/haproxy/configuration/{{ .PathParentType }}/{parent_name}/tcp_checks:
    get:
      summary: Return an array of all TCP Checks
      description: Returns all TCP Checks that are configured in specified {{ .ParentType }}.
      operationId: getAllTCPCheck{{ .ParentType }}
      tags:
        - TCPCheck
      parameters:
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tcp_checks'
        'default':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/DefaultError'
    put:
      summary: Replace a TCP Check list
      description: Replaces a whole list of TCP Checks with the list given in parameter for the specified {{ .ParentType }}.
      operationId: replaceAllTCPCheck{{ .ParentType }}
      tags:
        - TCPCheck
      parameters:
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tcp_checks'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tcp_checks'
        '200':
          description: All TCP Checks replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tcp_checks'
        '400':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        'default':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
  /services/haproxy/configuration/{{ .PathParentType }}/{parent_name}/tcp_checks/{index}:
    get:
      summary: Return one TCP Check
      description: Returns one TCP Check configuration by its index in the specified {{ .ParentType }}.
      operationId: getTCPCheck{{ .ParentType }}
      tags:
        - TCPCheck
      parameters:
        - name: index
          in: path
          description: TCP Check Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tcp_check'
        '404':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/DefaultError'
    post:
      summary: Add a new TCP Check
      description: Adds a new TCP Check of the specified type in the specified {{ .ParentType }}.
      operationId: createTCPCheck{{ .ParentType }}
      tags:
        - TCPCheck
      parameters:
        - name: index
          in: path
          description: TCP Check Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tcp_check'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tcp_check'
        '201':
          description: TCP Check created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tcp_check'
        '409':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/AlreadyExists'
        '400':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        'default':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
    put:
      summary: Replace a TCP Check
      description: Replaces a TCP Check configuration by its index in the specified {{ .ParentType }}.
      operationId: replaceTCPCheck{{ .ParentType }}
      tags:
        - TCPCheck
      parameters:
        - name: index
          in: path
          description: TCP Check Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tcp_check'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tcp_check'
        '200':
          description: TCP Check replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tcp_check'
        '400':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/BadRequest'
        '404':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/DefaultError'
      x-codegen-request-body-name: data
    delete:
      summary: Delete a TCP Check
      description: Deletes a TCP Check configuration by its index from the specified {{ .ParentType }}.
      operationId: deleteTCPCheck{{ .ParentType }}
      tags:
        - TCPCheck
      parameters:
        - name: index
          in: path
          description: TCP Check Index
          required: true
          schema:
            type: integer
        - name: parent_name
          in: path
          description: Parent name
          required: true
          schema:
            type: string
            pattern: '^[^\r\n<>*;$#&{}"]+$'
        - name: transaction_id
          in: query
          description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has its own version.
          required: false
          schema:
            type: integer
        - name: force_reload
          in: query
          description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
        '204':
          description: TCP Check deleted
        '404':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/NotFound'
        'default':
          $ref: '../../../../models/common/responses/models.yaml#/components/responses/DefaultError'
{{ end }}
