name: HAProxy check commit message
on:
  pull_request:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: commit-policy
        uses: docker://ghcr.io/haproxytech/commit-check:5.0.4
        env:
          API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
